[package]
name = "error-code"
version = "0.1.0"
edition = "2021"

[dependencies]

error-code-derive = { workspace = true }
base64 = "0.22.1"

[dev-dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
http = { workspace = true }
