[workspace]
members = ["error-code", "error-code-derive"]
default-members = ["error-code"]

resolver = "2"

[workspace.dependencies]
error-code = { path = "./error-code" }
error-code-derive = { path = "./error-code-derive" }
anyhow = "1"
http = "1"
thiserror = "1"
