[package]
name = "error-code-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.63", features = ["extra-traits"] }
darling = "0.20.9"
proc-macro2 = "1.0.82"
quote = "1.0.36"
